version: '3.9'

services:

  node:
    image: node:17-alpine
    container_name: 'diff_sync-next'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    environment:
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}

  tests:
    image: node:17-alpine
    container_name: 'jest'
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    environment:
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
