name: Tests
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm test